### ISSUE TITLE
Server crash when Initializing quests.

### ISSUE THREAD

**Issue by Whyy0416** [ike3/mangosbot-zero#21]
Thank you for this great project!!!
The server often crash when it says 'Initializing quests...', but when I disable playerbot, the server didn't crash.
By the way, I used a localized database.
what I have done:
1: use aiplayerbot.conf in src\modules\Bots\playerbot;
2: patched all sql files in src\modules\Bots\sql;
3: replaced ahbot.conf by ahbot.conf in src\modules\Bots\ahbot;
did I miss anything, or where can I get an Install guide?

**Comment by conan513** [comment]
https://github.com/conan513/mangosbot-zero/commit/4d60afdc246c0bf1e63036f8b28b1598c2a2e839

**Comment by Whyy0416** [comment]
@conan513
Understood. Thank you very much!
