### ISSUE TITLE
Suggestion: Allow setting admin level for player bots from other accounts to config file

### ISSUE THREAD

**Issue by Trystanosaurus** [ike3/mangosbot-zero#22]
I noticed that over the development of the bot a check was added to line 150 of PlayerbotMgr.cpp so that unless you're an admin you can't add player bots if they're not on your account.

Unfortunately the way I play my server is to have one character on each of several accounts, so that if needed I can also multi-box them.

I know it's easy enough to edit/comment out that check but would it be better to have a setting in the config where you could put in the gmlevel required to spawn to bots from other accounts (from 0 to 3).

If this isn't something you'd want, please feel free to close this issue, I just thought I'd make the suggestion. Thanks for all of your work on the bots, they're really good fun to play with.

**Comment by Lidocian** [comment]
why you not using guildbots?
if i remember correctly,when every of your bots is in the same guild you can add/invite/control it regardless of account.

**Comment by Trystanosaurus** [comment]
Ah, I didn't know being in the same guild allowed you to add them. I'll do that instead. Thanks  for the help!
