### ISSUE TITLE
Chatfilters

### ISSUE THREAD

**Issue by Lidocian** [ike3/mangosbot-zero#3]
All chatfilter working(@tank,@dps,  etc..) exept @heal and @melee - @ranged

![heal](https://cloud.githubusercontent.com/assets/22845183/19887940/e1cbe9fa-a02b-11e6-9c5f-28cac22d45bc.png)

on fully prot talented paladin (with just tank orders) are we need using @tank chat filter and @ranged?

![paladin](https://cloud.githubusercontent.com/assets/22845183/19888556/9a10b2fe-a02f-11e6-9df1-05253f8be010.png)

**Comment by ike3** [comment]
Yep this is a bug. Seems fixed in 8bc54fae11cca5762e8ffc86d1547dc5561a70d2
