### ISSUE TITLE
PlayerbotFactory. cpp at  PlayerbotFactory::InitInventorySkill()  Line 1417

### ISSUE THREAD

**Issue by Lidocian** [ike3/mangosbot-zero#4]
Hello Sergey!

in PlayerbotFactory. cpp at  PlayerbotFactory::InitInventorySkill()  Line 1417
should be?:

if (bot->HasSkill(SKILL_ENCHANTING)) {
        StoreItem(16207, 1); // Runed Arcanite Rod

**Comment by ike3** [comment]
Fixed in ab44283827c05d00aed6e4c0abf1fc5247786fe9
