### ISSUE TITLE
LootRollAction cpp. /disenchatnt needroll

### ISSUE THREAD

**Issue by Lidocian** [ike3/mangosbot-zero#6]
Could you use it?

Line 37-47

case ITEM_CLASS_WEAPON:
            case ITEM_CLASS_ARMOR:
                if (QueryItemUsage(proto))
                    vote = ROLL_NEED;
				**else if (bot->HasSkill(SKILL_ENCHANTING))
                    vote = ROLL_NEED;  //or greed?**
                break;
            default:
                if (IsLootAllowed(itemId))
                    vote = ROLL_NEED;
                break;

**Comment by ike3** [comment]
Should be fine after 8679df85766e4f414f7aaa81bb52d50cc69ecf6b

`disenchant` loot strategy must be active and the bot will loot the BoE disenchants. (`ll disenchant` or use a button in my lua addon) He won't roll though (bot will loot it when all other members passed) this is a bug but I am not sure which is better.

The new code is:
            if (IsLootAllowed(itemId, bot->GetPlayerbotAI()))
            {
                vote = ROLL_NEED;
                break;
            }

Seems the condition is false for some reason

**Comment by Lidocian** [comment]
The "roll" is more BLIZZLIKE
