### ISSUE TITLE
Segmentation fault under linux

### ISSUE THREAD

**Issue by conan513** [ike3/mangosbot-zero#9]
System:
CPU: FX-8120
RAM: 16GB
GPU: GTX970
OS: Arch Linux
DB: MariaDB 10.1.9

Mangosd crashing everytime when a few bots logged in, no crash if bots disabled.
No more info in debug mode.

38 GameObjects, 288 Creatures, and 0 Corpses/Bones loaded for grid 991 on map 0
Creating player data for himself 1397
Player Biayisuled added to map 0
WORLD: Sent SMSG_FRIEND_LIST
WORLD: Sent SMSG_IGNORE_LIST
Sending SMSG_INIT_WORLD_STATES to Map:0, Zone: 12
STORAGE: DestroyZoneLimitedItem in map 0 and area 12
Sending SMSG_SPELL_GO id=836
Spell 836 Effect0 : 46 Targets: Player Biayisuled (Guid: 1397), -, -
WORLD: Spell Effect DUMMY
3/255 Bot Biayisuled logged in
Player: channels cleaned up!
Segmentation fault (core dump)

full world server log
http://pastebin.com/7quFNw45

**Comment by ike3** [comment]
There is no crash information in the log. I noticed that in Windows it is printed to stdout but not reflected in the log. Maybe the same issue persists in linux.

P.S. Try to clean AI tables by re-running `src\modules\Bots\sql\characters_ai_playerbot.sql`

**Comment by conan513** [comment]
clearing tables not helped but I'm keep looking to find the problem
